### ISSUE TITLE
May I ask for the permission of CP-VASP version 2

### ISSUE THREAD

**Issue by linguolu** [yuanyue-liu-group/CP-VASP#10]
To whom it may concern,

I hope this message finds you well. I have recently come across the innovative method developed by your group, CP-HS-DM, in several current articles, particularly in the context of constant potential calculations. I am very impressed by its capabilities and potential applications.

I previously submitted a request for permission to use the CP-HS-DM method, but I haven’t yet received a response. I wanted to kindly follow up to see if you might consider granting permission. 

Thank you very much for your time and consideration. Please let me know if there’s any additional information I can provide to assist with the request.

Best regards,
Linguo Lu

**Comment by ZLevell** [comment]
Dear Linguo,

We have sent you an email with access to the patch files. Are you able to download them?

**Comment by linguolu** [comment]
Dear Zlevell,

Good afternoon. Thank you for your response!

Yes, I have received the email and downloaded the patch. I appreciate your
contribution to the development of the CP calculation!

Best regards,
Linguo Lu

ZLevell ***@***.***> 于2024年11月13日周三 13:02写道：

**Comment by ZLevell** [comment]
I'm glad you were able to get the patch. Happy coding!
