### ISSUE TITLE
Report error in AIMD with CP-VASP (version 2)

### ISSUE THREAD

**Issue by luoweiok** [yuanyue-liu-group/CP-VASP#4]
Dear Dr. Liu
I recently tried to do AIMD with CP-VASP (version 2), it always reported an error after runing for a while:
ERROR FEXCP: supplied Exchange-correletion table is too small, maximal index : 5678. ---->  I REFUSE TO CONTINUE WITH THIS SICK JOB ... BYE!!! <----
What causes this problem? How can I solve this problem?
<img width="588" alt="7d6dee0013786027e5ae70d238d9785" src="https://github.com/user-attachments/assets/6c1aaa25-8586-4ee7-b3ce-a4f4027c80b9">

With best regard, Wei Luo

**Comment by ZLevell** [comment]
Dear Wei Luo,

This error can sometimes occur if the geometry becomes unreasonable. Could you share your final structure? I'm also curious if the last SCF cycle successfully converged - if not, then the forces may be significantly wrong and break the simulation.

**Comment by luoweiok** [comment]
Dear Dr. Liu
Thank you for your timely advice. This is indeed an error caused by the unreasonable initial structure. After my adjustment, this error has been solved.
With best regard, Wei Luo

**Comment by ZLevell** [comment]
I'm glad it worked, good luck with your simulations.
