### ISSUE TITLE
Missing CPM-ion lines in VASP output file and OSZICAR file

### ISSUE THREAD

**Issue by POP-CAT-flow** [yuanyue-liu-group/CP-VASP#5]
I am currently working with CP-VASP, specifically the version associated with VASPsol++, and have encountered an issue that I need some help with. We have successfully applied the CP-VASP patch to VASP 6.3.2, and I have ensured that the additional CPM-related information was included in src/main.F as specified. After patching, we recompiled VASP without any errors.

However, when running the provided example for Ionic Relaxation Calculation, I noticed that the output did not include the expected CPM-ion information. Specifically, in the OSZICAR file, after each ionic step, there is no occurrence of the "CPM-ion" line, which should display additional details such as the electrolyte-referenced Fermi level, target energy, and grand canonical energy.

Could you please advise on why the CPM-ion line might not be appearing as expected? Attached files as follows:
[IonicRelaxation.zip](https://github.com/user-attachments/files/17374742/IonicRelaxation.zip)

Thank you very much for your time and assistance.

**Comment by ZLevell** [comment]
Dear minyuan,

Thank you for reaching out. Your input files look correct. Could you try recompiling from scratch and double check that your job is running the right executable? It looks like the job is performing regular VASPsol++.

**Comment by POP-CAT-flow** [comment]
Dear Zachary Levell,

Thank you for your response. 
After recompiling, We were able to successfully run the calculation.

**Comment by POP-CAT-flow** [comment]
Dear Zachary Levell,

We  were able to run the first three examples without any issues. However, when we tried running the MolecularDynamics-GrandCanonical example, we encountered an error:

```
ERROR: NLPCM_solver: your 'vacuum' region is not large enough to accommodate the necessary counter charge.
The counter charge is exceeding 99% of the saturation value.
```

We checked the structure used in this example, and it already has 35 Å in the Z direction. The input parameters are exactly the same as those provided in the example. We are not sure what might be causing this problem. I have attached a zip file containing our test results for your reference 
[Uploading MolecularDynamics-GrandCanonical.zip…]()
.

Thank you very much for your assistance.

**Comment by ZLevell** [comment]
Dear minyuan,

I'm glad the compilation worked. For grand-canonical MD, one of the challenges is that the variance in the electron number can be quite high, so the supercells often need to be quite tall. We've also observed that running MD with the same inputs and code on different supercomputers can lead to different results, so you may have simply been unlucky. If the speed isn't bad, I'd recommend trying again with a height of 40 Å. You can also try the VASPsol version.
