### ISSUE TITLE
ERROR: NLPCM_solver: your 'vacuum' region is not large enough to accommodate the necessary counter charge

### ISSUE THREAD

**Issue by h757062840** [yuanyue-liu-group/CP-VASP#7]
When I use CP-VASP to relax the Cu-H2O interface with H2O molecules, no matter how I change the INCAR parameters, an error report will appear like below:
**ERROR: NLPCM_solver: your 'vacuum' region is not large enough to accommodate the necessary counter charge The counter charge is exceeding 99% of the saturation value Maximum charge:   7.736436851330858E-002 Surface/solute charge:   0.100039409635883**   
  
In fact, my vacuum layer is already large enough (slab is 8 angstroms, vacuum layer is 22 angstroms).How to solve this problem？
Thank you very much for your time and assistance.

**Comment by ZLevell** [comment]
Thank you for your question. We are currently looking into how this issue can be solved. 

What is the surface-normalized charge density of your system? If the charge is high, you may need to increase the vacuum size further. It might be worthwhile trying to relax the system with regular VASPsol++ (without the constant-potential) using the electron number predicted by CP-VASP. If that doesn't work, the VASPsol++ team may be able to assist you. You can also try using the regular VASPsol version of CP-VASP which does not require the same vacuum size (although I'd still recommend using 10 angstroms as the bare minimum).

**Comment by Rshiran** [comment]
hello friend,I encountered the same problem last month, and it was solved by modifying the vacuum height to be greater than 15 angstroms. You can try to modify the vacuum height
